In [2]:

# No terminal, uma vez: python -m pip install openpyxl pandas
import pandas as pd
import openpyxl

In [3]:
path = r"H:\Python\TERCEIRA_ETAPA\Atividade_03\Tabela_11_Domicilios_sem_presenca_de_conjuge_e_com_filhos.xlsx"

# Sexo da pessoa responsável pelo domicílio

In [5]:
#Lé todas as abas do arquivo
todas = pd.read_excel(path, sheet_name=None, header=None)
print(todas.keys())

dict_keys(['BR GR UF MU', 'Tabela base do SIDRA 9882'])

In [6]:
bruto = pd.read_excel(path, sheet_name="Tabela base do SIDRA 9882", header=None)

In [7]:
bruto

,0,1,2,3
0,"Tabela 9882 - Domicílios particulares, por pre...",NaN,NaN,NaN
1,Variável - Domicílios particulares (Domicílios),NaN,NaN,NaN
2,Ano - 2022,NaN,NaN,NaN
3,"Brasil, Grande Região, Unidade da Federação e ...",Sexo da pessoa responsável pelo domicílio,NaN,NaN
4,NaN,Total,Homens,Mulheres
...,...,...,...,...
5604,Vicentinópolis (GO),352,55,297
5605,Vila Boa (GO),226,37,189
5606,Vila Propício (GO),267,49,218
5607,Brasília (DF),184921,24110,160811
5608,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN

In [8]:
indicador_2 = bruto.iloc[5:5608].copy()

In [9]:
indicador_2

                        0         1        2         3
5                  Brasil  11936510  1614739  10321771
6                   Norte    909212   149246    759966
7                Nordeste   3487048   411968   3075080
8                 Sudeste   5105674   700511   4405163
9                     Sul   1537469   228801   1308668
...                   ...       ...      ...       ...
5603      Vianópolis (GO)       689       87       602
5604  Vicentinópolis (GO)       352       55       297
5605        Vila Boa (GO)       226       37       189
5606   Vila Propício (GO)       267       49       218
5607        Brasília (DF)    184921    24110    160811

[5603 rows x 4 columns]

In [11]:
# Preenchendo os nomes das colunas
indicador_2.columns = [
    "regiao",
    "total",
    "homens",
    "mulheres",
]

In [12]:
indicador_2 = indicador_2.reset_index(drop=True)

# horas são número, não texto
for col in indicador_2.columns[1:]:
    indicador_2[col] = pd.to_numeric(indicador_2[col], errors="coerce")

indicador_2

                   regiao     total   homens  mulheres
0                  Brasil  11936510  1614739  10321771
1                   Norte    909212   149246    759966
2                Nordeste   3487048   411968   3075080
3                 Sudeste   5105674   700511   4405163
4                     Sul   1537469   228801   1308668
...                   ...       ...      ...       ...
5598      Vianópolis (GO)       689       87       602
5599  Vicentinópolis (GO)       352       55       297
5600        Vila Boa (GO)       226       37       189
5601   Vila Propício (GO)       267       49       218
5602        Brasília (DF)    184921    24110    160811

[5603 rows x 4 columns]

In [13]:
indicador_2.describe()

              total        homens      mulheres
count  5.603000e+03  5.603000e+03  5.603000e+03
mean   8.521513e+03  1.152767e+03  7.368746e+03
std    1.879794e+05  2.535391e+04  1.626494e+05
min    2.300000e+01  3.000000e+00  1.600000e+01
25%    2.500000e+02  4.000000e+01  2.090000e+02
50%    5.660000e+02  8.700000e+01  4.730000e+02
75%    1.323500e+03  1.890000e+02  1.134000e+03
max    1.193651e+07  1.614739e+06  1.032177e+07

In [14]:
indicador_2.describe().round(2)

             total      homens     mulheres
count      5603.00     5603.00      5603.00
mean       8521.51     1152.77      7368.75
std      187979.37    25353.91    162649.37
min          23.00        3.00        16.00
25%         250.00       40.00       209.00
50%         566.00       87.00       473.00
75%        1323.50      189.00      1134.00
max    11936510.00  1614739.00  10321771.00

EXCLUIR AS CIDADES, REPAREM NO PADRÃO, ELAS TEM O () QUE INDICAM O UF

In [18]:
indicador_2 = indicador_2[~indicador_2["regiao"].str.contains(r"\(", na=False)]
indicador_2

                 regiao     total   homens  mulheres
0                Brasil  11936510  1614739  10321771
1                 Norte    909212   149246    759966
2              Nordeste   3487048   411968   3075080
3               Sudeste   5105674   700511   4405163
4                   Sul   1537469   228801   1308668
5          Centro-Oeste    897107   124213    772894
6              Rondônia     78597    12520     66077
7                  Acre     47506     7166     40340
8              Amazonas    205036    37693    167343
9               Roraima     31690     5072     26618
10                 Pará    423309    67853    355456
11                Amapá     42958     7288     35670
12            Tocantins     80116    11654     68462
13             Maranhão    384488    50219    334269
14                Piauí    192425    23505    168920
15                Ceará    558869    64440    494429
16  Rio Grande do Norte    204565    24132    180433
17              Paraíba    240849    27585    213264
18           Pernambuco    598783    64573    534210
19              Alagoas    192706    21961    170745
20              Sergipe    155980    16312    139668
21                Bahia    958383   119241    839142
22         Minas Gerais   1258188   171679   1086509
23       Espírito Santo    214564    30152    184412
24       Rio de Janeiro   1067294   146596    920698
25            São Paulo   2565628   352084   2213544
26               Paraná    593410    85773    507637
27       Santa Catarina    340157    53269    286888
28    Rio Grande do Sul    603902    89759    514143
29   Mato Grosso do Sul    150374    21034    129340
30          Mato Grosso    172804    26431    146373
31                Goiás    389008    52638    336370
32     Distrito Federal    184921    24110    160811

# Trazer a Tabela 1.1.1 (horas de trabalho doméstico) e juntar com indicador_2

In [26]:
# Mesma limpeza da Aula 2: linhas 8–40, nomes de coluna, horas como número
path_horas = r"H:\Python\TERCEIRA_ETAPA\Atividade_03\Tabela 1.1.1.xls"

bruto_1 = pd.read_excel(path_horas, engine="xlrd", header=None)

indicador_1 = bruto_1.iloc[8:41].copy()
indicador_1.columns = [
    "uf_regiao",
    "total",
    "total_branca",
    "total_preta_parda",
    "homem_branca",
    "homem_preta_parda",
    "mulher_branca",
    "mulher_preta_parda",
]
indicador_1 = indicador_1.reset_index(drop=True)
for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")

indicador_1

,uf_regiao,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
7,Amapá,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
9,Nordeste,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
10,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
12,Ceará,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
14,Paraíba,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
15,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
16,Alagoas,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
17,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
19,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
20,Minas Gerais,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
21,Espírito Santo,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
24,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
25,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
26,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
28,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
29,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [27]:
# Left join: fica tudo de indicador_2; puxa as horas da 1.1.1 quando o nome bate
# suffixes: as duas tabelas têm coluna "total" — domicílios vs horas
indicador1e2 = indicador_2.merge(
    indicador_1,
    how="left",
    left_on="regiao",
    right_on="uf_regiao",
    suffixes=("_domicilios", "_horas"),
)
indicador1e2 = indicador1e2.drop(columns=["uf_regiao"])

In [28]:
indicador1e2 = indicador1e2.rename(columns={
    "homens": "resp_domicilio_homens",
    "mulheres": "resp_domicilio_mulheres",
})
indicador1e2

,regiao,total_domicilios,resp_domicilio_homens,resp_domicilio_mulheres,total_horas,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,11936510,1614739,10321771,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,909212,149246,759966,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Nordeste,3487048,411968,3075080,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
3,Sudeste,5105674,700511,4405163,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
4,Sul,1537469,228801,1308668,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
5,Centro-Oeste,897107,124213,772894,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
6,Rondônia,78597,12520,66077,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
7,Acre,47506,7166,40340,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
8,Amazonas,205036,37693,167343,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
9,Roraima,31690,5072,26618,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
10,Pará,423309,67853,355456,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
11,Amapá,42958,7288,35670,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
12,Tocantins,80116,11654,68462,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
13,Maranhão,384488,50219,334269,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
14,Piauí,192425,23505,168920,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
15,Ceará,558869,64440,494429,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
16,Rio Grande do Norte,204565,24132,180433,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
17,Paraíba,240849,27585,213264,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
18,Pernambuco,598783,64573,534210,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
19,Alagoas,192706,21961,170745,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
20,Sergipe,155980,16312,139668,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
21,Bahia,958383,119241,839142,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
22,Minas Gerais,1258188,171679,1086509,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
23,Espírito Santo,214564,30152,184412,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
24,Rio de Janeiro,1067294,146596,920698,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
25,São Paulo,2565628,352084,2213544,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
26,Paraná,593410,85773,507637,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
27,Santa Catarina,340157,53269,286888,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
28,Rio Grande do Sul,603902,89759,514143,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
29,Mato Grosso do Sul,150374,21034,129340,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,172804,26431,146373,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,389008,52638,336370,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,184921,24110,160811,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [29]:
# % de domicílios com responsável mulher  |  horas médias das mulheres (média das duas raças)
indicador1e2["pct_resp_mulheres"] = (
    indicador1e2["resp_domicilio_mulheres"] / indicador1e2["total_domicilios"] * 100
)
indicador1e2["horas_mulher"] = (
    indicador1e2["mulher_branca"] + indicador1e2["mulher_preta_parda"]
) / 2

indicador1e2[
    ["regiao", "pct_resp_mulheres", "horas_mulher", "resp_domicilio_mulheres", "total_domicilios"]
].sort_values("pct_resp_mulheres", ascending=False)

,regiao,pct_resp_mulheres,horas_mulher,resp_domicilio_mulheres,total_domicilios
20,Sergipe,89.542249,23.689292,139668,155980
18,Pernambuco,89.215960,23.800638,534210,598783
19,Alagoas,88.603884,24.975146,170745,192706
17,Paraíba,88.546766,23.839293,213264,240849
15,Ceará,88.469570,23.985996,494429,558869
16,Rio Grande do Norte,88.203261,23.984982,180433,204565
2,Nordeste,88.185766,23.230691,3075080,3487048
14,Piauí,87.784851,22.094752,168920,192425
21,Bahia,87.558106,22.894924,839142,958383
32,Distrito Federal,86.962000,18.522728,160811,184921
13,Maranhão,86.938734,20.310323,334269,384488
0,Brasil,86.472269,21.221052,10321771,11936510
31,Goiás,86.468659,19.014378,336370,389008
22,Minas Gerais,86.355060,22.631200,1086509,1258188
3,Sudeste,86.279755,21.361700,4405163,5105674
25,São Paulo,86.276888,21.269403,2213544,2565628
24,Rio de Janeiro,86.264703,20.080735,920698,1067294
5,Centro-Oeste,86.154049,18.775862,772894,897107
29,Mato Grosso do Sul,86.012210,19.067981,129340,150374
23,Espírito Santo,85.947316,21.330544,184412,214564
26,Paraná,85.545744,19.131020,507637,593410
12,Tocantins,85.453592,19.646556,68462,80116
28,Rio Grande do Sul,85.136827,18.987975,514143,603902
4,Sul,85.118334,19.175851,1308668,1537469
7,Acre,84.915590,16.420553,40340,47506
30,Mato Grosso,84.704636,18.239374,146373,172804
27,Santa Catarina,84.339878,19.530669,286888,340157
6,Rondônia,84.070639,20.737149,66077,78597
9,Roraima,83.994951,16.348061,26618,31690
10,Pará,83.970811,20.713127,355456,423309
1,Norte,83.585126,19.914984,759966,909212
11,Amapá,83.034592,16.278533,35670,42958
8,Amazonas,81.616399,19.740977,167343,205036

pct_resp_mulheres = em cada 100 desses domicílios, quantos têm mulher responsável.
horas_mulher = média semanal de horas das mulheres (média simples de branca e preta/parda na 1.1.1).
Como ler os dois juntos. Nordeste concentra os dois: Sergipe ~90% de responsáveis mulheres e ~24 h; Alagoas ~89% e ~25 h (mais horas). Norte tem menos lares com responsável mulher (Amazonas ~82%) e menos horas (Amapá, Acre, Roraima ~16 h). DF é o contraste: muitas responsáveis mulheres (~87%) e menos horas (~18,5 h).

In [30]:
# Neste recorte (sem cônjuge + com filhos): mulheres são maioria?
indicador_2["mais_mulheres"] = indicador_2["mulheres"] > indicador_2["homens"]

brasil = indicador_2.loc[indicador_2["regiao"] == "Brasil"].iloc[0]
print("Brasil — domicílios sem cônjuge e com filhos (Censo 2022)")
print(f"  mulheres: {int(brasil.mulheres):,}  ({brasil.mulheres/brasil.total*100:.1f}%)")
print(f"  homens:   {int(brasil.homens):,}  ({brasil.homens/brasil.total*100:.1f}%)")
print(f"  {brasil.mulheres/brasil.homens:.1f} mulheres para cada homem responsável")
print()
print("Em todas as UFs/regiões mulheres > homens?", indicador_2["mais_mulheres"].all())

indicador_2[["regiao", "homens", "mulheres", "mais_mulheres"]]

Brasil — domicílios sem cônjuge e com filhos (Censo 2022)
  mulheres: 10,321,771  (86.5%)
  homens:   1,614,739  (13.5%)
  6.4 mulheres para cada homem responsável

Em todas as UFs/regiões mulheres > homens? True

                 regiao   homens  mulheres  mais_mulheres
0                Brasil  1614739  10321771           True
1                 Norte   149246    759966           True
2              Nordeste   411968   3075080           True
3               Sudeste   700511   4405163           True
4                   Sul   228801   1308668           True
5          Centro-Oeste   124213    772894           True
6              Rondônia    12520     66077           True
7                  Acre     7166     40340           True
8              Amazonas    37693    167343           True
9               Roraima     5072     26618           True
10                 Pará    67853    355456           True
11                Amapá     7288     35670           True
12            Tocantins    11654     68462           True
13             Maranhão    50219    334269           True
14                Piauí    23505    168920           True
15                Ceará    64440    494429           True
16  Rio Grande do Norte    24132    180433           True
17              Paraíba    27585    213264           True
18           Pernambuco    64573    534210           True
19              Alagoas    21961    170745           True
20              Sergipe    16312    139668           True
21                Bahia   119241    839142           True
22         Minas Gerais   171679   1086509           True
23       Espírito Santo    30152    184412           True
24       Rio de Janeiro   146596    920698           True
25            São Paulo   352084   2213544           True
26               Paraná    85773    507637           True
27       Santa Catarina    53269    286888           True
28    Rio Grande do Sul    89759    514143           True
29   Mato Grosso do Sul    21034    129340           True
30          Mato Grosso    26431    146373           True
31                Goiás    52638    336370           True
32     Distrito Federal    24110    160811           True

In [31]:

# TABELA 3 - Censo Demográfico 2022

dados = {
    "regiao": [
        "Brasil", "Norte", "Nordeste", "Sudeste", "Sul", "Centro-Oeste",
        "Rondônia", "Acre", "Amazonas", "Roraima", "Pará", "Amapá",
        "Tocantins", "Maranhão", "Piauí", "Ceará", "Rio Grande do Norte",
        "Paraíba", "Pernambuco", "Alagoas", "Sergipe", "Bahia",
        "Minas Gerais", "Espírito Santo", "Rio de Janeiro", "São Paulo",
        "Paraná", "Santa Catarina", "Rio Grande do Sul",
        "Mato Grosso do Sul", "Mato Grosso", "Goiás", "Distrito Federal"
    ],

    # Total de pessoas com curso superior completo
    "superior_homens": [
        10478534, 590558, 1744994, 5391638, 1678865, 982489,
        62766, 33291, 141059, 25585, 229285, 35082,
        63485, 161352, 108371, 285013, 131178,
        147221, 321587, 98462, 80609, 411202,
        1031532, 193756, 942645, 3223705,
        695425, 489554, 583873, 145341, 173267, 350828, 313054
    ],

    "superior_mulheres": [
        13577575, 934609, 3003939, 7437191, 2570005, 1430013,
        101866, 51009, 201507, 41460, 371811, 54106,
        112851, 307329, 196584, 474290, 208735,
        243521, 530893, 169534, 137646, 735406,
        1583902, 297344, 1301062, 4254883,
        992505, 672958, 904542, 220908, 276997, 528443, 403665
    ],

    # Ciência, Tecnologia, Engenharias e Matemática
    "ctem_homens": [
        2750422, 133055, 389993, 1588874, 427372, 211124,
        11863, 6237, 34749, 4958, 55481, 7464,
        12304, 33820, 21680, 32808, 16686,
        33369, 73253, 21398, 17596, 94556,
        291778, 49648, 265723, 981724,
        166579, 126554, 132420, 28241, 33307, 74711, 74866
    ],

    "ctem_mulheres": [
        1398169, 76601, 231395, 739247, 235543, 115834,
        8675, 4128, 17919, 3057, 31211, 3885,
        7724, 21248, 15467, 35126, 16459,
        18855, 47007, 12198, 11422, 53612,
        160479, 26018, 140805, 411944,
        89056, 59188, 87300, 18100, 23468, 42156, 32109
    ],

    # Educação, Serviços pessoais, Saúde e Bem-estar
    "educacao_servicos_saude_homens": [
        8079707, 1677998, 1822087, 3652397, 1256291, 749148,
        63584, 33379, 121988, 23977, 248397, 36754,
        71705, 206222, 128416, 294578, 135434,
        150862, 281695, 106971, 83176, 434735,
        832482, 161332, 612263, 2046321,
        501471, 333537, 421284, 128352, 141121, 288616, 191061
    ],

    "educacao_servicos_saude_mulheres": [
        6041723, 458616, 1458181, 2884108, 1007718, 593101,
        49262, 24258, 91249, 18098, 190270, 26960,
        58158, 165555, 102457, 229996, 107161,
        120837, 224362, 86911, 66376, 354528,
        674521, 131544, 466399, 1611645,
        403280, 265964, 338472, 101443, 114069, 232052, 145538
    ]
}

df = pd.DataFrame(dados)

# 1. HOMENS E MULHERES POR REGIÃO COM CURSO SUPERIOR
indicador_1 = df[
    ["regiao", "superior_homens", "superior_mulheres"]
].copy()

indicador_1 = indicador_1.rename(columns={
    "superior_homens": "homens",
    "superior_mulheres": "mulheres"
})

indicador_1["total"] = indicador_1["homens"] + indicador_1["mulheres"]

print("TABELA 1 - PESSOAS COM CURSO SUPERIOR COMPLETO")
display(indicador_1)

# 2. HOMENS E MULHERES COM CURSO NAS ÁREAS DE
# CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA

indicador_2 = df[
    ["regiao", "ctem_homens", "ctem_mulheres"]
].copy()

indicador_2 = indicador_2.rename(columns={
    "ctem_homens": "homens",
    "ctem_mulheres": "mulheres"
})

indicador_2["total"] = indicador_2["homens"] + indicador_2["mulheres"]

print("TABELA 2 - CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA")
display(indicador_2)

# 3. HOMENS E MULHERES COM CURSO NAS ÁREAS DE
# EDUCAÇÃO, SERVIÇOS PESSOAIS, SAÚDE E BEM-ESTAR

indicador_3 = df[
    [
        "regiao",
        "educacao_servicos_saude_homens",
        "educacao_servicos_saude_mulheres"
    ]
].copy()

indicador_3 = indicador_3.rename(columns={
    "educacao_servicos_saude_homens": "homens",
    "educacao_servicos_saude_mulheres": "mulheres"
})

indicador_3["total"] = indicador_3["homens"] + indicador_3["mulheres"]

print("TABELA 3 - EDUCAÇÃO, SERVIÇOS PESSOAIS, SAÚDE E BEM-ESTAR")
display(indicador_3)

# ESTATÍSTICAS DESCRITIVAS - TABELA 1

print("ESTATÍSTICAS DESCRITIVAS - CURSO SUPERIOR")
display(indicador_1[["homens", "mulheres", "total"]].describe())

# ESTATÍSTICAS DESCRITIVAS - TABELA 2

print("ESTATÍSTICAS DESCRITIVAS - CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA")
display(indicador_2[["homens", "mulheres", "total"]].describe())

# ESTATÍSTICAS DESCRITIVAS - TABELA 3

print("ESTATÍSTICAS DESCRITIVAS - EDUCAÇÃO, SERVIÇOS PESSOAIS, SAÚDE E BEM-ESTAR")
display(indicador_3[["homens", "mulheres", "total"]].describe())

# ANÁLISE: ONDE HÁ MAIS MULHERES?

indicador_1["mais_mulheres"] = indicador_1["mulheres"] > indicador_1["homens"]

indicador_2["mais_mulheres"] = indicador_2["mulheres"] > indicador_2["homens"]

indicador_3["mais_mulheres"] = indicador_3["mulheres"] > indicador_3["homens"]

# VERIFICAÇÃO DO BRASIL - CURSO SUPERIOR

brasil_1 = indicador_1.loc[
    indicador_1["regiao"] == "Brasil"
].iloc[0]

print("Brasil — Pessoas com curso superior completo")
print(f"  Mulheres: {int(brasil_1.mulheres):,} "
      f"({brasil_1.mulheres/brasil_1.total*100:.1f}%)")

print(f"  Homens:   {int(brasil_1.homens):,} "
      f"({brasil_1.homens/brasil_1.total*100:.1f}%)")

print(f"  {brasil_1.mulheres/brasil_1.homens:.1f} mulheres para cada homem")

# VERIFICAÇÃO DO BRASIL - CTEM

brasil_2 = indicador_2.loc[
    indicador_2["regiao"] == "Brasil"
].iloc[0]

print("\nBrasil — Ciência, Tecnologia, Engenharias e Matemática")
print(f"  Mulheres: {int(brasil_2.mulheres):,} "
      f"({brasil_2.mulheres/brasil_2.total*100:.1f}%)")

print(f"  Homens:   {int(brasil_2.homens):,} "
      f"({brasil_2.homens/brasil_2.total*100:.1f}%)")

print(f"  {brasil_2.homens/brasil_2.mulheres:.1f} homens para cada mulher")

# VERIFICAÇÃO DO BRASIL - EDUCAÇÃO, SERVIÇOS E SAÚDE

brasil_3 = indicador_3.loc[
    indicador_3["regiao"] == "Brasil"
].iloc[0]

print("\nBrasil — Educação, Serviços pessoais, Saúde e Bem-estar")
print(f"  Mulheres: {int(brasil_3.mulheres):,} "
      f"({brasil_3.mulheres/brasil_3.total*100:.1f}%)")

print(f"  Homens:   {int(brasil_3.homens):,} "
      f"({brasil_3.homens/brasil_3.total*100:.1f}%)")

print(f"  {brasil_3.mulheres/brasil_3.homens:.1f} mulheres para cada homem")

# MOSTRAR APENAS REGIÃO, HOMENS, MULHERES E INDICADOR

print("\n--- Curso superior ---")
display(
    indicador_1[
        ["regiao", "homens", "mulheres", "mais_mulheres"]
    ]
)

print("\n--- Ciência, Tecnologia, Engenharias e Matemática ---")
display(
    indicador_2[
        ["regiao", "homens", "mulheres", "mais_mulheres"]
    ]
)

print("\n--- Educação, Serviços pessoais, Saúde e Bem-estar ---")
display(
    indicador_3[
        ["regiao", "homens", "mulheres", "mais_mulheres"]
    ]
)

TABELA 1 - PESSOAS COM CURSO SUPERIOR COMPLETO

                 regiao    homens  mulheres     total
0                Brasil  10478534  13577575  24056109
1                 Norte    590558    934609   1525167
2              Nordeste   1744994   3003939   4748933
3               Sudeste   5391638   7437191  12828829
4                   Sul   1678865   2570005   4248870
5          Centro-Oeste    982489   1430013   2412502
6              Rondônia     62766    101866    164632
7                  Acre     33291     51009     84300
8              Amazonas    141059    201507    342566
9               Roraima     25585     41460     67045
10                 Pará    229285    371811    601096
11                Amapá     35082     54106     89188
12            Tocantins     63485    112851    176336
13             Maranhão    161352    307329    468681
14                Piauí    108371    196584    304955
15                Ceará    285013    474290    759303
16  Rio Grande do Norte    131178    208735    339913
17              Paraíba    147221    243521    390742
18           Pernambuco    321587    530893    852480
19              Alagoas     98462    169534    267996
20              Sergipe     80609    137646    218255
21                Bahia    411202    735406   1146608
22         Minas Gerais   1031532   1583902   2615434
23       Espírito Santo    193756    297344    491100
24       Rio de Janeiro    942645   1301062   2243707
25            São Paulo   3223705   4254883   7478588
26               Paraná    695425    992505   1687930
27       Santa Catarina    489554    672958   1162512
28    Rio Grande do Sul    583873    904542   1488415
29   Mato Grosso do Sul    145341    220908    366249
30          Mato Grosso    173267    276997    450264
31                Goiás    350828    528443    879271
32     Distrito Federal    313054    403665    716719

TABELA 2 - CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA

                 regiao   homens  mulheres    total
0                Brasil  2750422   1398169  4148591
1                 Norte   133055     76601   209656
2              Nordeste   389993    231395   621388
3               Sudeste  1588874    739247  2328121
4                   Sul   427372    235543   662915
5          Centro-Oeste   211124    115834   326958
6              Rondônia    11863      8675    20538
7                  Acre     6237      4128    10365
8              Amazonas    34749     17919    52668
9               Roraima     4958      3057     8015
10                 Pará    55481     31211    86692
11                Amapá     7464      3885    11349
12            Tocantins    12304      7724    20028
13             Maranhão    33820     21248    55068
14                Piauí    21680     15467    37147
15                Ceará    32808     35126    67934
16  Rio Grande do Norte    16686     16459    33145
17              Paraíba    33369     18855    52224
18           Pernambuco    73253     47007   120260
19              Alagoas    21398     12198    33596
20              Sergipe    17596     11422    29018
21                Bahia    94556     53612   148168
22         Minas Gerais   291778    160479   452257
23       Espírito Santo    49648     26018    75666
24       Rio de Janeiro   265723    140805   406528
25            São Paulo   981724    411944  1393668
26               Paraná   166579     89056   255635
27       Santa Catarina   126554     59188   185742
28    Rio Grande do Sul   132420     87300   219720
29   Mato Grosso do Sul    28241     18100    46341
30          Mato Grosso    33307     23468    56775
31                Goiás    74711     42156   116867
32     Distrito Federal    74866     32109   106975

TABELA 3 - EDUCAÇÃO, SERVIÇOS PESSOAIS, SAÚDE E BEM-ESTAR

                 regiao   homens  mulheres     total
0                Brasil  8079707   6041723  14121430
1                 Norte  1677998    458616   2136614
2              Nordeste  1822087   1458181   3280268
3               Sudeste  3652397   2884108   6536505
4                   Sul  1256291   1007718   2264009
5          Centro-Oeste   749148    593101   1342249
6              Rondônia    63584     49262    112846
7                  Acre    33379     24258     57637
8              Amazonas   121988     91249    213237
9               Roraima    23977     18098     42075
10                 Pará   248397    190270    438667
11                Amapá    36754     26960     63714
12            Tocantins    71705     58158    129863
13             Maranhão   206222    165555    371777
14                Piauí   128416    102457    230873
15                Ceará   294578    229996    524574
16  Rio Grande do Norte   135434    107161    242595
17              Paraíba   150862    120837    271699
18           Pernambuco   281695    224362    506057
19              Alagoas   106971     86911    193882
20              Sergipe    83176     66376    149552
21                Bahia   434735    354528    789263
22         Minas Gerais   832482    674521   1507003
23       Espírito Santo   161332    131544    292876
24       Rio de Janeiro   612263    466399   1078662
25            São Paulo  2046321   1611645   3657966
26               Paraná   501471    403280    904751
27       Santa Catarina   333537    265964    599501
28    Rio Grande do Sul   421284    338472    759756
29   Mato Grosso do Sul   128352    101443    229795
30          Mato Grosso   141121    114069    255190
31                Goiás   288616    232052    520668
32     Distrito Federal   191061    145538    336599

ESTATÍSTICAS DESCRITIVAS - CURSO SUPERIOR

             homens      mulheres         total
count  3.300000e+01  3.300000e+01  3.300000e+01
mean   9.498668e+05  1.343306e+06  2.293173e+06
std    2.019606e+06  2.654125e+06  4.671895e+06
min    2.558500e+04  4.146000e+04  6.704500e+04
25%    1.311780e+05  2.015070e+05  3.399130e+05
50%    2.850130e+05  4.036650e+05  7.167190e+05
75%    6.954250e+05  9.925050e+05  1.687930e+06
max    1.047853e+07  1.357758e+07  2.405611e+07

ESTATÍSTICAS DESCRITIVAS - CIÊNCIA, TECNOLOGIA, ENGENHARIAS E MATEMÁTICA

             homens      mulheres         total
count  3.300000e+01  3.300000e+01  3.300000e+01
mean   2.486246e+05  1.271335e+05  3.757581e+05
std    5.496228e+05  2.706692e+05  8.198146e+05
min    4.958000e+03  3.057000e+03  8.015000e+03
25%    2.168000e+04  1.645900e+04  3.714700e+04
50%    5.548100e+04  3.210900e+04  8.669200e+04
75%    1.665790e+05  8.905600e+04  2.556350e+05
max    2.750422e+06  1.398169e+06  4.148591e+06

ESTATÍSTICAS DESCRITIVAS - EDUCAÇÃO, SERVIÇOS PESSOAIS, SAÚDE E BEM-ESTAR

             homens      mulheres         total
count  3.300000e+01  3.300000e+01  3.300000e+01
mean   7.671922e+05  5.710549e+05  1.338247e+06
std    1.520832e+06  1.143641e+06  2.659106e+06
min    2.397700e+04  1.809800e+04  4.207500e+04
25%    1.283520e+05  1.014430e+05  2.297950e+05
50%    2.483970e+05  1.902700e+05  4.386670e+05
75%    6.122630e+05  4.586160e+05  1.078662e+06
max    8.079707e+06  6.041723e+06  1.412143e+07

Brasil — Pessoas com curso superior completo
  Mulheres: 13,577,575 (56.4%)
  Homens:   10,478,534 (43.6%)
  1.3 mulheres para cada homem

Brasil — Ciência, Tecnologia, Engenharias e Matemática
  Mulheres: 1,398,169 (33.7%)
  Homens:   2,750,422 (66.3%)
  2.0 homens para cada mulher

Brasil — Educação, Serviços pessoais, Saúde e Bem-estar
  Mulheres: 6,041,723 (42.8%)
  Homens:   8,079,707 (57.2%)
  0.7 mulheres para cada homem

--- Curso superior ---

                 regiao    homens  mulheres  mais_mulheres
0                Brasil  10478534  13577575           True
1                 Norte    590558    934609           True
2              Nordeste   1744994   3003939           True
3               Sudeste   5391638   7437191           True
4                   Sul   1678865   2570005           True
5          Centro-Oeste    982489   1430013           True
6              Rondônia     62766    101866           True
7                  Acre     33291     51009           True
8              Amazonas    141059    201507           True
9               Roraima     25585     41460           True
10                 Pará    229285    371811           True
11                Amapá     35082     54106           True
12            Tocantins     63485    112851           True
13             Maranhão    161352    307329           True
14                Piauí    108371    196584           True
15                Ceará    285013    474290           True
16  Rio Grande do Norte    131178    208735           True
17              Paraíba    147221    243521           True
18           Pernambuco    321587    530893           True
19              Alagoas     98462    169534           True
20              Sergipe     80609    137646           True
21                Bahia    411202    735406           True
22         Minas Gerais   1031532   1583902           True
23       Espírito Santo    193756    297344           True
24       Rio de Janeiro    942645   1301062           True
25            São Paulo   3223705   4254883           True
26               Paraná    695425    992505           True
27       Santa Catarina    489554    672958           True
28    Rio Grande do Sul    583873    904542           True
29   Mato Grosso do Sul    145341    220908           True
30          Mato Grosso    173267    276997           True
31                Goiás    350828    528443           True
32     Distrito Federal    313054    403665           True

--- Ciência, Tecnologia, Engenharias e Matemática ---

                 regiao   homens  mulheres  mais_mulheres
0                Brasil  2750422   1398169          False
1                 Norte   133055     76601          False
2              Nordeste   389993    231395          False
3               Sudeste  1588874    739247          False
4                   Sul   427372    235543          False
5          Centro-Oeste   211124    115834          False
6              Rondônia    11863      8675          False
7                  Acre     6237      4128          False
8              Amazonas    34749     17919          False
9               Roraima     4958      3057          False
10                 Pará    55481     31211          False
11                Amapá     7464      3885          False
12            Tocantins    12304      7724          False
13             Maranhão    33820     21248          False
14                Piauí    21680     15467          False
15                Ceará    32808     35126           True
16  Rio Grande do Norte    16686     16459          False
17              Paraíba    33369     18855          False
18           Pernambuco    73253     47007          False
19              Alagoas    21398     12198          False
20              Sergipe    17596     11422          False
21                Bahia    94556     53612          False
22         Minas Gerais   291778    160479          False
23       Espírito Santo    49648     26018          False
24       Rio de Janeiro   265723    140805          False
25            São Paulo   981724    411944          False
26               Paraná   166579     89056          False
27       Santa Catarina   126554     59188          False
28    Rio Grande do Sul   132420     87300          False
29   Mato Grosso do Sul    28241     18100          False
30          Mato Grosso    33307     23468          False
31                Goiás    74711     42156          False
32     Distrito Federal    74866     32109          False

--- Educação, Serviços pessoais, Saúde e Bem-estar ---

                 regiao   homens  mulheres  mais_mulheres
0                Brasil  8079707   6041723          False
1                 Norte  1677998    458616          False
2              Nordeste  1822087   1458181          False
3               Sudeste  3652397   2884108          False
4                   Sul  1256291   1007718          False
5          Centro-Oeste   749148    593101          False
6              Rondônia    63584     49262          False
7                  Acre    33379     24258          False
8              Amazonas   121988     91249          False
9               Roraima    23977     18098          False
10                 Pará   248397    190270          False
11                Amapá    36754     26960          False
12            Tocantins    71705     58158          False
13             Maranhão   206222    165555          False
14                Piauí   128416    102457          False
15                Ceará   294578    229996          False
16  Rio Grande do Norte   135434    107161          False
17              Paraíba   150862    120837          False
18           Pernambuco   281695    224362          False
19              Alagoas   106971     86911          False
20              Sergipe    83176     66376          False
21                Bahia   434735    354528          False
22         Minas Gerais   832482    674521          False
23       Espírito Santo   161332    131544          False
24       Rio de Janeiro   612263    466399          False
25            São Paulo  2046321   1611645          False
26               Paraná   501471    403280          False
27       Santa Catarina   333537    265964          False
28    Rio Grande do Sul   421284    338472          False
29   Mato Grosso do Sul   128352    101443          False
30          Mato Grosso   141121    114069          False
31                Goiás   288616    232052          False
32     Distrito Federal   191061    145538          False